[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/hubspot-auth/*"
  to = "https://api.hubapi.com/oauth/v1/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/hubspot-api/*"
  to = "https://api.hubapi.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_FIREBASE_API_KEY = "${VITE_FIREBASE_API_KEY}"
  VITE_FIREBASE_AUTH_DOMAIN = "${VITE_FIREBASE_AUTH_DOMAIN}"
  VITE_FIREBASE_PROJECT_ID = "${VITE_FIREBASE_PROJECT_ID}"
  VITE_FIREBASE_STORAGE_BUCKET = "${VITE_FIREBASE_STORAGE_BUCKET}"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "${VITE_FIREBASE_MESSAGING_SENDER_ID}"
  VITE_FIREBASE_APP_ID = "${VITE_FIREBASE_APP_ID}"
  VITE_FIREBASE_MEASUREMENT_ID = "${VITE_FIREBASE_MEASUREMENT_ID}"
  VITE_HUBSPOT_APP_ID = "${VITE_HUBSPOT_APP_ID}"
  VITE_HUBSPOT_CLIENT_ID = "${VITE_HUBSPOT_CLIENT_ID}"
  VITE_HUBSPOT_CLIENT_SECRET = "${VITE_HUBSPOT_CLIENT_SECRET}"
  VITE_HUBSPOT_REDIRECT_URI = "${VITE_HUBSPOT_REDIRECT_URI}"
  VITE_HUBSPOT_SCOPES = "${VITE_HUBSPOT_SCOPES}"